### ISSUE TITLE
[Feature] Support reporting from blob

### ISSUE THREAD

**Issue by hampsterx** [cenfun/monocart-reporter#162]
https://playwright.dev/docs/test-sharding

https://timdeschryver.dev/blog/merging-your-playwright-sharded-reports-into-a-single-html-report
https://hasangurhan.medium.com/merging-playwright-sharded-reports-on-gitlab-3e85875328c2

--

Would be great if monocart could support this feature rather than its own custom merge feature.

related: https://github.com/cenfun/monocart-reporter/issues/144

Is there some technical reason it cant be supported?

Monocart reporter is better in numerous ways than the standard "html" reporter but the shard support via blob is superior for CI/CD runs. For now we have had to revert to "html" but its a shame to have to do this.

**Comment by cenfun** [comment]
> Monocart reporter is better in numerous ways than the standard "html" reporter

It is because monocart collects a lot of additional information while running, but bolb reporter does not.
Therefore, it is worthless to merge reports from bolb into monocart, you can use the standard html reporter directly.

Monocart also supports mergeing from shards, and the latest version supports `.zip` file too (similar to bolb), see 
https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#merge-shard-reports

**Comment by hampsterx** [comment]
> > Monocart reporter is better in numerous ways than the standard "html" reporter
> 
> It is because monocart collects a lot of additional information while running and testing, like custom fields in comments, cpu/memory usage and so on, but bolb reporter does not. Therefore, it is worthless to merge reports from bolb into monocart, you can use the standard html reporter directly.
> 
> Monocart also supports mergeing from shards, and the latest version supports `.zip` file too (sets option `zip` to true, it similar to bolb), see https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#merge-shard-reports

yep fair enough, we had been using the merge from shards feature.

Its unfortunate but good to know.
