### ISSUE TITLE
[Improve] Column resize on main report page

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#41]
Currently there is no visual indication to the user that he can resize the columns in the main page of the report:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/07abd870-1bea-406c-9ff1-9badf14ba7cd)

If the user tries to mouse over along the column line he will eventually find that the mouse cursor changes to indicate he can resize the column:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/0e0d1762-16fd-40b2-a67a-8583f61478a3)

If possible consider two things:
1) Add some visual indication, like a simple vertical bar is probably enough, for the columns on the top row so the user knows where he can click and hold to resize the column.
2) Allow auto-resizing when using double click. Double clicking the delimiter for a column, the place we can click and hold to resize the column, should try to auto resize that column to fit the content. For instance, in the first image, if I double clicked the delimiter for the title column it should auto-resize the column to enough width to fit the text from all titles. If if can't fit the full text of the column being auto resized then it should expand to the max possible value.

**Comment by cenfun** [comment]
1, Actually, the grid can use another theme [lightblue](https://cenfun.github.io/turbogrid/formatter.html#theme=lightblue), which can display the vertical lines of each column, but if there are too many lines, it may make our eyes feel tired if viewed for a long time. Maybe resize is not a high-frequency action when the default title width is improved.
2, `auto-resizing` should be really difficult to implement. We only render these rows in the viewable area to improve performance. Imagine that there may be a million rows, so the column width is difficult to get by calculation content, because not all content is rendered.

**Comment by edumserrano** [comment]
1. You're right, you could consider exposing the option for the theme for the user to select or is that too messy? More importantly I think you're right, if we tackle #40 then we can probably just close this one as "won't do" at least for now.

2. That's a fair point. I thought it was going to be hard, I just asked about it because it's a behaviour some apps allow you to do and it was something I tried immediately when I first tried to resize the column. I'm fine with not doing this until somehow there's more people asking for it.
