### ISSUE TITLE
Insufficient function and branch coverage

### ISSUE THREAD

**Issue by azamat-sharapov** [cenfun/monocart-reporter#74]
![image](https://github.com/cenfun/monocart-reporter/assets/3023661/f3b81490-aef8-4d82-a466-ef5ca1f606bf)

In our monorepo, we have been having problems with function and branch coverage in LCOV files recently. [Here I have slimmed down](https://github.com/azamat-sharapov/monocart-coverage-repro) our big repository to smaller size and added instructions to README for setup.

Following no more valid, even commenting out lines in vite config produces incorrect function and branch report:
<del>However, if you [comment out these lines](https://github.com/azamat-sharapov/monocart-coverage-repro/blob/main/apps/web/vite.config.ts#L23-L39) and re-generate LCOV file, you will have `100%` coverage.</del>
<del>I don't know what is relation between Vue unplugin plugin and monocart, but I hope you could give some clue.</del>

**Comment by cenfun** [comment]
after checked your repo, it used the v8 format data (page.coverage.startJSCoverage + stopJSCoverage), so the v8 data needs to be converted to the istanbul format, because lcov report requires istanbul format data.
The problem is that this conversion is not perfect, functions or branches is not absolutely correct sometimes.
see diffirents [compare-reports](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#compare-reports)

So please try using istanbul data (see [istanbul workflows](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#compare-workflows)), then the lcov report will shows perfect functions and branches. 

I don't know how to use [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) with vite, may be you can try this plugin
https://www.npmjs.com/package/vite-plugin-istanbul

**Comment by azamat-sharapov** [comment]
Thanks for looking into it. Actually previously my setup was with vite-plugin-istanbul and I didn't have luck with it. Then switched to v8 with monorepo and it was working perfectly. But then, as you can see, vue unplugin plugin is conflicting with setup and causing these issues. If there is nothing else we can do about it, then we can close issue.

**Comment by cenfun** [comment]
Thanks for the feedback. we will continue to looking into the conversion between v8 and istanbul.

**Comment by azamat-sharapov** [comment]
@cenfun I've tried latest v2.1.1, thanks for your hard work. Unfortunately coverage report for functions, branches and lines are still incorrect. I've updated the repository (see description for the link).

**Comment by cenfun** [comment]
@azamat-sharapov thanks for the repo. 
Please try adding one more option ` minify: false` for vite, sometimes the sourcemap not works well with minified code.
```js
// https://vitejs.dev/config/
export default defineConfig(() => {
  return {
    build: {
      sourcemap: true,
      minify: false
    },
```
then I can get follwing report:
![image](https://github.com/cenfun/monocart-reporter/assets/334577/242247fa-d9dd-499b-a6dd-a64640a1d6f2)

**Comment by azamat-sharapov** [comment]
@cenfun thanks a lot for help! I've now disabled minification for e2e tests only. I got different coverage report now (with some uncovered lines), which I think is correct report.
