### ISSUE TITLE
(feat) Code coverage numbers ignore components within scope that aren't touched by tests

### ISSUE THREAD

**Issue by vespoli95** [cenfun/monocart-reporter#77]
Hi, our overall code coverage numbers seem to be artificially high, due to the fact that this library seems to ignore files that aren't touched by the tests when calculating coverage.

For example, I have many files under the `src/components` path that is shown below that I know have no coverage, and these files are ignored in my coverage report.
![image](https://github.com/cenfun/monocart-reporter/assets/20251812/19b8e589-e88d-4d51-b49d-6ddee3772066)

**I believe instead that ALL files within scope, as set by sourceFilter, should show up in the coverage report, so that files with no coverage actually _bring down_ the overall coverage number.**

**Comment by cenfun** [comment]
Did you using `v8` format report?

There are two filters you can try: `entryFilter` and `sourceFilter`

for example following are the files you input via v8 coverage API
1, dist/main.js
2, dist/vendor.js
3, dist/some-else-bundle.js

first, we should remove 2 and 3 with `entryFilter` because those files are not in our coverage scope.

if there is a sourcemap `dist/main.js.map` existing, the `dist/main.js` will be extracted to source files like:

a, src/index.js
b, src/components/app.js
c, node_modules/module/name.js

we can remove `node_modules/module/name.js` with `sourceFilter`, because we only care about the coverage files which is in `src` folder.
